In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repr

[[5282, 5966, 7184, 8941],
 [5282, 5966, 7184, 6473],
 [5282, 8914, 7184, 6269],
 [1163, 4089, 2587, 6025, 3888],
 [1163, 4089, 2587, 6025, 8798],
 [6059, 5282, 5210, 7184, 8398],
 [9238, 735, 4029, 6025]]

In [7]:
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8

In [10]:
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 5282 5966 7184 8941]
 [   0    0    0    0 5282 5966 7184 6473]
 [   0    0    0    0 5282 8914 7184 6269]
 [   0    0    0 1163 4089 2587 6025 3888]
 [   0    0    0 1163 4089 2587 6025 8798]
 [   0    0    0 6059 5282 5210 7184 8398]
 [   0    0    0    0 9238  735 4029 6025]]


In [11]:
dim = 10

In [12]:
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Embedding

model = Sequential([
    Input(shape=(8,), dtype='int32'),
    Embedding(input_dim=10000, output_dim=10)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step


array([[[-4.11305800e-02,  3.07966806e-02, -3.45152840e-02,
          1.72477402e-02, -4.31125276e-02,  1.86335929e-02,
          4.65265252e-02,  3.33149917e-02,  3.48691456e-02,
         -1.95397977e-02],
        [-4.11305800e-02,  3.07966806e-02, -3.45152840e-02,
          1.72477402e-02, -4.31125276e-02,  1.86335929e-02,
          4.65265252e-02,  3.33149917e-02,  3.48691456e-02,
         -1.95397977e-02],
        [-4.11305800e-02,  3.07966806e-02, -3.45152840e-02,
          1.72477402e-02, -4.31125276e-02,  1.86335929e-02,
          4.65265252e-02,  3.33149917e-02,  3.48691456e-02,
         -1.95397977e-02],
        [-4.11305800e-02,  3.07966806e-02, -3.45152840e-02,
          1.72477402e-02, -4.31125276e-02,  1.86335929e-02,
          4.65265252e-02,  3.33149917e-02,  3.48691456e-02,
         -1.95397977e-02],
        [ 2.31306590e-02,  3.50110196e-02, -2.29357835e-02,
         -1.77489743e-02,  3.35291140e-02, -2.19035894e-04,
         -4.77899238e-03,  1.44744851e-02, -1.404874

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5282, 5966, 7184, 8941], dtype=int32)

In [16]:
model.predict(embedded_docs)[1][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([-0.04113058,  0.03079668, -0.03451528,  0.01724774, -0.04311253,
        0.01863359,  0.04652653,  0.03331499,  0.03486915, -0.0195398 ],
      dtype=float32)